[project]
name = "kdctl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = []

[project.scripts]
kdctl = "kdctl:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
